[package]
name = "lazyhex"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = { version = "3.2.1", default-features = false }
clap = { version = "4.4.2", features = ["derive"] }
crossterm = "0.27.0"
ratatui = { version = "0.23.0", features = ["all-widgets"]}
similar = "2.2.1"
