[package]
name = "lazyhex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
crossterm = "0.27.0"
ratatui = { version = "0.23.0", features = ["all-widgets"]}
